# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lngrYncjm_K1QDZSPxY_6QWxoJN7EpVJ
"""

import random

words = ["apple", "house", "train", "water", "robot"]
word = random.choice(words)
guessed = ['_'] * len(word)
attempts = 6
guessed_letters = []

print("Welcome to Hangman!")

while attempts > 0 and '_' in guessed:
    print("\nWord: " + ' '.join(guessed))
    print(f"Guesses left: {attempts}")
    guess = input("Guess a letter: ").lower()

    if guess in guessed_letters:
        print("You already guessed that letter.")
        continue

    guessed_letters.append(guess)

    if guess in word:
        for i, letter in enumerate(word):
            if letter == guess:
                guessed[i] = guess
    else:
        print("Wrong guess!")
        attempts -= 1

if '_' not in guessed:
    print(f"\nCongratulations! You guessed the word: {word}")
else:
    print(f"\nGame Over! The word was: {word}")